#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _A_reg(void);
extern void _AMPA_reg(void);
extern void _AMPAr_reg(void);
extern void _clampex_reg(void);
extern void _cp2_reg(void);
extern void _cp_reg(void);
extern void _field_reg(void);
extern void _GABAa_reg(void);
extern void _GABAar_reg(void);
extern void _GABAb_reg(void);
extern void _GABAbr_reg(void);
extern void _H_reg(void);
extern void _Iahp_reg(void);
extern void _Ican_reg(void);
extern void _IL3_reg(void);
extern void _IL_reg(void);
extern void _infot_reg(void);
extern void _intf__reg(void);
extern void _intfsw_reg(void);
extern void _kdr2_reg(void);
extern void _kmbg_reg(void);
extern void _misc_reg(void);
extern void _naf2_reg(void);
extern void _nap_reg(void);
extern void _NMDA_reg(void);
extern void _NMDAr_reg(void);
extern void _nthh_reg(void);
extern void _ntIh_reg(void);
extern void _ntt_reg(void);
extern void _OFThpo_reg(void);
extern void _OFThresh_reg(void);
extern void _pregencv_reg(void);
extern void _stats_reg(void);
extern void _updown_reg(void);
extern void _vecst_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," A.mod");
    fprintf(stderr," AMPA.mod");
    fprintf(stderr," AMPAr.mod");
    fprintf(stderr," clampex.mod");
    fprintf(stderr," cp2.mod");
    fprintf(stderr," cp.mod");
    fprintf(stderr," field.mod");
    fprintf(stderr," GABAa.mod");
    fprintf(stderr," GABAar.mod");
    fprintf(stderr," GABAb.mod");
    fprintf(stderr," GABAbr.mod");
    fprintf(stderr," H.mod");
    fprintf(stderr," Iahp.mod");
    fprintf(stderr," Ican.mod");
    fprintf(stderr," IL3.mod");
    fprintf(stderr," IL.mod");
    fprintf(stderr," infot.mod");
    fprintf(stderr," intf_.mod");
    fprintf(stderr," intfsw.mod");
    fprintf(stderr," kdr2.mod");
    fprintf(stderr," kmbg.mod");
    fprintf(stderr," misc.mod");
    fprintf(stderr," naf2.mod");
    fprintf(stderr," nap.mod");
    fprintf(stderr," NMDA.mod");
    fprintf(stderr," NMDAr.mod");
    fprintf(stderr," nthh.mod");
    fprintf(stderr," ntIh.mod");
    fprintf(stderr," ntt.mod");
    fprintf(stderr," OFThpo.mod");
    fprintf(stderr," OFThresh.mod");
    fprintf(stderr," pregencv.mod");
    fprintf(stderr," stats.mod");
    fprintf(stderr," updown.mod");
    fprintf(stderr," vecst.mod");
    fprintf(stderr, "\n");
  }
  _A_reg();
  _AMPA_reg();
  _AMPAr_reg();
  _clampex_reg();
  _cp2_reg();
  _cp_reg();
  _field_reg();
  _GABAa_reg();
  _GABAar_reg();
  _GABAb_reg();
  _GABAbr_reg();
  _H_reg();
  _Iahp_reg();
  _Ican_reg();
  _IL3_reg();
  _IL_reg();
  _infot_reg();
  _intf__reg();
  _intfsw_reg();
  _kdr2_reg();
  _kmbg_reg();
  _misc_reg();
  _naf2_reg();
  _nap_reg();
  _NMDA_reg();
  _NMDAr_reg();
  _nthh_reg();
  _ntIh_reg();
  _ntt_reg();
  _OFThpo_reg();
  _OFThresh_reg();
  _pregencv_reg();
  _stats_reg();
  _updown_reg();
  _vecst_reg();
}
